export enum CONTENT_TYPE {
  관광지 = 12,
  문화시설 = 14,
  축제공연행사 = 15,
  여행코스 = 25,
  레포츠 = 28,
  숙박 = 32,
  쇼핑 = 38,
  음식점 = 39,
}

export enum SIDO_CODE {
  서울 = 1,
  인천 = 2,
  대전 = 3,
  대구 = 4,
  광주 = 5,
  부산 = 6,
  울산 = 7,
  세종특별자치시 = 8,
  경기도 = 31,
  강원도 = 32,
  충청북도 = 33,
  충청남도 = 34,
  경상북도 = 35,
  경상남도 = 36,
  전라북도 = 37,
  전라남도 = 38,
  제주도 = 39,
}

export const sidoCodeList = [
  { key: 1, name: "서울" },
  { key: 2, name: "인천" },
  { key: 3, name: "대전" },
  { key: 4, name: "대구" },
  { key: 5, name: "광주" },
  { key: 6, name: "부산" },
  { key: 7, name: "울산" },
  { key: 8, name: "세종특별자치시" },
  { key: 31, name: "경기도" },
  { key: 32, name: "강원도" },
  { key: 33, name: "충청북도" },
  { key: 34, name: "충청남도" },
  { key: 35, name: "경상북도" },
  { key: 36, name: "경상남도" },
  { key: 37, name: "전라북도" },
  { key: 38, name: "전라남도" },
  { key: 39, name: "제주도" },
];

export const sidoGugunMap = [
  {
    sidoKey: SIDO_CODE.서울,
    gugunList: [
      { key: 1, name: "강남구" },
      { key: 2, name: "강동구" },
      { key: 3, name: "강북구" },
      { key: 4, name: "강서구" },
      { key: 5, name: "관악구" },
      { key: 6, name: "광진구" },
      { key: 7, name: "구로구" },
      { key: 8, name: "금천구" },
      { key: 9, name: "노원구" },
      { key: 10, name: "도봉구" },
      { key: 11, name: "동대문구" },
      { key: 12, name: "동작구" },
      { key: 13, name: "마포구" },
      { key: 14, name: "서대문구" },
      { key: 15, name: "서초구" },
      { key: 16, name: "성동구" },
      { key: 17, name: "성북구" },
      { key: 18, name: "송파구" },
      { key: 19, name: "양천구" },
      { key: 20, name: "영등포구" },
      { key: 21, name: "용산구" },
      { key: 22, name: "은평구" },
      { key: 23, name: "종로구" },
      { key: 24, name: "중구" },
      { key: 25, name: "중랑구" },
    ],
  },
  {
    sidoKey: SIDO_CODE.인천,
    gugunList: [
      { key: 1, name: "강화군" },
      { key: 2, name: "계양구" },
      { key: 3, name: "미추홀구" },
      { key: 4, name: "남동구" },
      { key: 5, name: "동구" },
      { key: 6, name: "부평구" },
      { key: 7, name: "서구" },
      { key: 8, name: "연수구" },
      { key: 9, name: "옹진군" },
      { key: 10, name: "중구" },
    ],
  },
  {
    sidoKey: SIDO_CODE.대전,
    gugunList: [
      { key: 1, name: "대덕구" },
      { key: 2, name: "동구" },
      { key: 3, name: "서구" },
      { key: 4, name: "유성구" },
      { key: 5, name: "중구" },
    ],
  },
  {
    sidoKey: SIDO_CODE.대전,
    gugunList: [
      { key: 1, name: "남구" },
      { key: 2, name: "달서구" },
      { key: 3, name: "달성군" },
      { key: 4, name: "동구" },
      { key: 5, name: "북구" },
      { key: 6, name: "서구" },
      { key: 7, name: "수성구" },
      { key: 8, name: "중구" },
    ],
  },
  {
    sidoKey: SIDO_CODE.광주,
    gugunList: [
      { key: 1, name: "광산구" },
      { key: 2, name: "남구" },
      { key: 3, name: "동구" },
      { key: 4, name: "북구" },
      { key: 5, name: "서구" },
    ],
  },
  {
    sidoKey: SIDO_CODE.부산,
    gugunList: [
      { key: 1, name: "강서구" },
      { key: 2, name: "금정구" },
      { key: 3, name: "기장군" },
      { key: 4, name: "남구" },
      { key: 5, name: "동구" },
      { key: 6, name: "동래구" },
      { key: 7, name: "부산진구" },
      { key: 8, name: "북구" },
      { key: 9, name: "사상구" },
      { key: 10, name: "사하구" },
      { key: 11, name: "서구" },
      { key: 12, name: "수영구" },
      { key: 13, name: "연제구" },
      { key: 14, name: "영도구" },
      { key: 15, name: "중구" },
      { key: 16, name: "해운대구" },
    ],
  },
  {
    sidoKey: SIDO_CODE.울산,
    gugunList: [
      { key: 1, name: "중구" },
      { key: 2, name: "남구" },
      { key: 3, name: "동구" },
      { key: 4, name: "북구" },
      { key: 5, name: "울주군" },
    ],
  },

  {
    sidoKey: SIDO_CODE.세종특별자치시,
    gugunList: [{ key: 1, name: "세종특별자치시" }],
  },

  {
    sidoKey: SIDO_CODE.경기도,
    gugunList: [
      { key: 1, name: "가평군" },
      { key: 2, name: "고양시" },
      { key: 3, name: "과천시" },
      { key: 4, name: "광명시" },
      { key: 5, name: "광주시" },
      { key: 6, name: "구리시" },
      { key: 7, name: "군포시" },
      { key: 8, name: "김포시" },
      { key: 9, name: "남양주시" },
      { key: 10, name: "동두천시" },
      { key: 11, name: "부천시" },
      { key: 12, name: "성남시" },
      { key: 13, name: "수원시" },
      { key: 14, name: "시흥시" },
      { key: 15, name: "안산시" },
      { key: 16, name: "안성시" },
      { key: 17, name: "안양시" },
      { key: 18, name: "양주시" },
      { key: 19, name: "양평군" },
      { key: 20, name: "여주시" },
      { key: 21, name: "연천군" },
      { key: 22, name: "오산시" },
      { key: 23, name: "용인시" },
      { key: 24, name: "의왕시" },
      { key: 25, name: "의정부시" },
      { key: 26, name: "이천시" },
      { key: 27, name: "파주시" },
      { key: 28, name: "평택시" },
      { key: 29, name: "포천시" },
      { key: 30, name: "하남시" },
      { key: 31, name: "화성시" },
    ],
  },

  {
    sidoKey: SIDO_CODE.강원도,
    gugunList: [
      { key: 1, name: "강릉시" },
      { key: 2, name: "고성군" },
      { key: 3, name: "동해시" },
      { key: 4, name: "삼척시" },
      { key: 5, name: "속초시" },
      { key: 6, name: "양구군" },
      { key: 7, name: "양양군" },
      { key: 8, name: "영월군" },
      { key: 9, name: "원주시" },
      { key: 10, name: "인제군" },
      { key: 11, name: "정선군" },
      { key: 12, name: "철원군" },
      { key: 13, name: "춘천시" },
      { key: 14, name: "태백시" },
      { key: 15, name: "평창군" },
      { key: 16, name: "홍천군" },
      { key: 17, name: "화천군" },
      { key: 18, name: "횡성군" },
    ],
  },

  {
    sidoKey: SIDO_CODE.충청북도,
    gugunList: [
      { key: 1, name: "괴산군" },
      { key: 2, name: "단양군" },
      { key: 3, name: "보은군" },
      { key: 4, name: "영동군" },
      { key: 5, name: "옥천군" },
      { key: 6, name: "음성군" },
      { key: 7, name: "제천시" },
      { key: 8, name: "진천군" },
      { key: 9, name: "청원군" },
      { key: 10, name: "청주시" },
      { key: 11, name: "충주시" },
      { key: 12, name: "증평군" },
    ],
  },

  {
    sidoKey: SIDO_CODE.충청남도,
    gugunList: [
      { key: 1, name: "공주시" },
      { key: 2, name: "금산군" },
      { key: 3, name: "논산시" },
      { key: 4, name: "당진시" },
      { key: 5, name: "보령시" },
      { key: 6, name: "부여군" },
      { key: 7, name: "서산시" },
      { key: 8, name: "서천군" },
      { key: 9, name: "아산시" },
      { key: 11, name: "예산군" },
      { key: 12, name: "천안시" },
      { key: 13, name: "청양군" },
      { key: 14, name: "태안군" },
      { key: 15, name: "홍성군" },
      { key: 16, name: "계룡시" },
    ],
  },

  {
    sidoKey: SIDO_CODE.경상북도,
    gugunList: [
      { key: 1, name: "경산시" },
      { key: 2, name: "경주시" },
      { key: 3, name: "고령군" },
      { key: 4, name: "구미시" },
      { key: 5, name: "군위군" },
      { key: 6, name: "김천시" },
      { key: 7, name: "문경시" },
      { key: 8, name: "봉화군" },
      { key: 9, name: "상주시" },
      { key: 10, name: "성주군" },
      { key: 11, name: "안동시" },
      { key: 12, name: "영덕군" },
      { key: 13, name: "영양군" },
      { key: 14, name: "영주시" },
      { key: 15, name: "영천시" },
      { key: 16, name: "예천군" },
      { key: 17, name: "울릉군" },
      { key: 18, name: "울진군" },
      { key: 19, name: "의성군" },
      { key: 20, name: "청도군" },
      { key: 21, name: "청송군" },
      { key: 22, name: "칠곡군" },
      { key: 23, name: "포항시" },
    ],
  },

  {
    sidoKey: SIDO_CODE.경상남도,
    gugunList: [
      { key: 1, name: "거제시" },
      { key: 2, name: "거창군" },
      { key: 3, name: "고성군" },
      { key: 4, name: "김해시" },
      { key: 5, name: "남해군" },
      { key: 6, name: "마산시" },
      { key: 7, name: "밀양시" },
      { key: 8, name: "사천시" },
      { key: 9, name: "산청군" },
      { key: 10, name: "양산시" },
      { key: 12, name: "의령군" },
      { key: 13, name: "진주시" },
      { key: 14, name: "진해시" },
      { key: 15, name: "창녕군" },
      { key: 16, name: "창원시" },
      { key: 17, name: "통영시" },
      { key: 18, name: "하동군" },
      { key: 19, name: "함안군" },
      { key: 20, name: "함양군" },
      { key: 21, name: "합천군" },
    ],
  },

  {
    sidoKey: SIDO_CODE.전라북도,
    gugunList: [
      { key: 1, name: "고창군" },
      { key: 2, name: "군산시" },
      { key: 3, name: "김제시" },
      { key: 4, name: "남원시" },
      { key: 5, name: "무주군" },
      { key: 6, name: "부안군" },
      { key: 7, name: "순창군" },
      { key: 8, name: "완주군" },
      { key: 9, name: "익산시" },
      { key: 10, name: "임실군" },
      { key: 11, name: "장수군" },
      { key: 12, name: "전주시" },
      { key: 13, name: "정읍시" },
      { key: 14, name: "진안군" },
    ],
  },

  {
    sidoKey: SIDO_CODE.전라남도,
    gugunList: [
      { key: 1, name: "강진군" },
      { key: 2, name: "고흥군" },
      { key: 3, name: "곡성군" },
      { key: 4, name: "광양시" },
      { key: 5, name: "구례군" },
      { key: 6, name: "나주시" },
      { key: 7, name: "담양군" },
      { key: 8, name: "목포시" },
      { key: 9, name: "무안군" },
      { key: 10, name: "보성군" },
      { key: 11, name: "순천시" },
      { key: 12, name: "신안군" },
      { key: 13, name: "여수시" },
      { key: 16, name: "영광군" },
      { key: 17, name: "영암군" },
      { key: 18, name: "완도군" },
      { key: 19, name: "장성군" },
      { key: 20, name: "장흥군" },
      { key: 21, name: "진도군" },
      { key: 22, name: "함평군" },
      { key: 23, name: "해남군" },
      { key: 24, name: "화순군" },
    ],
  },

  {
    sidoKey: SIDO_CODE.제주도,
    gugunList: [
      { key: 1, name: "남제주군" },
      { key: 2, name: "북제주군" },
      { key: 3, name: "서귀포시" },
      { key: 4, name: "제주시" },
    ],
  },
];
