#### 127.0.0.1:8080/user/login

POST 127.0.0.1:8080/user/login
?userId="ssafy"
&userPass="ssafy"

#### 127.0.0.1:8080/user/logout
GET 127.0.0.1:8080/user/logout

#### 127.0.0.1:8080/user/join
POST 127.0.0.1:8080/user/join
{
    "userId" : "ssafy",
    "userPass" : "ssafy",
    "userName" : "김싸피",
    "emailId" : "ssafy12",
    "emailDomain" : "ssafy",
}